version: '3.7'
services:
  node1:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "9000:9000"
    volumes:
      - data/node1:/data
    command: server http://node{1...4}/data
  node2:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    volumes:
      - data/node2:/data
    command: server http://node{1...4}/data
  node3:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    volumes:
      - data/node3:/data
    command: server http://node{1...4}/data
  node4:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    volumes:
      - data/node4:/data
    command: server http://node{1...4}/data
